---
- hosts: webservers
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
        name: nginx
        state: started
      become: yes
    - name: copy the nginx config file and restat nginx
      copy:
        src: static_site.cfg
        dest: /etc/nginx/sites-available/static_site.cfg
      become: yes
    - name: Delete existing sites default
      file:
        path: /etc/nginx/sites-available/default 
        state: absent
      become: yes
    - name: create symlink
      file:
        src: /etc/nginx/sites-available/static_site.cfg
        dest: /etc/nginx/sites-available/default
        state: link
      become: yes
    - name: copy the content of the web site
      copy:
        src: static-site-src/
        dest: /home/natawut/static-site
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
